demoPro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('newApp.urls')),
    path('', include('hr.urls')),
    path('', include('employee.urls')),
    
]

hr/urls.py
# hr/urls.py

from django.urls import path
from .views import add_hr, hr_list

urlpatterns = [
    path('admin-dashboard/add-hr/', add_hr, name='add-hr'),
    path('admin-dashboard/hr-list/', hr_list, name='hr_list'),
]

hr/models.py
# hr/models.py

from django.db import models
from django.contrib.auth.models import User

class HR(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='profile_images/',null=True)
    emp_id = models.CharField(max_length=10, unique=True, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    password = models.CharField(max_length=128)

    def __str__(self):
        return self.user.username

hr/forms.py
# hr/forms.py

from django import forms
from django.contrib.auth.models import User
from .models import HR

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'first_name', 'last_name', 'email']

class HRForm(forms.ModelForm):
    class Meta:
        model = HR
        fields = ['profile_image', 'emp_id', 'name']

hr/views.py
# hr/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from .models import HR
from .forms import UserForm, HRForm
from django.contrib.auth import authenticate, login

def is_admin(user):
    return user.is_superuser

@login_required
@user_passes_test(is_admin)
def add_hr(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        password = request.POST.get('password')
        name = request.POST.get('name')
        emp_id = request.POST.get('emp_id')
        email = request.POST.get('email')
        profile_pic = request.FILES.get('profile_image')

        user = User.objects.create_user(
            username=username,
            password=password,
            email=email,
            first_name=first_name,
            last_name=last_name
        )
        hrdetails = HR(user=user, name=name, emp_id=emp_id, profile_image=profile_pic)
        hrdetails.save()
        return redirect('hr_list')
    return render(request, 'hr/add_hr.html')

@login_required
@user_passes_test(is_admin)
def hr_list(request):
    hrs = HR.objects.all()
    return render(request, 'hr/hr_list.html', {'hrs': hrs})

templates/hr/add_hr.html
<!-- hr/templates/hr/add_hr.html -->

{% extends 'newApp/adminbase.html' %}
<head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
{% block content %}
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 form-container">
                <h2 class="form-header text-center">Add HR </h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="id_first_name">First Name</label>
                            <input type="text" class="form-control" id="id_first_name" name="first_name" required>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="id_last_name">Last Name</label>
                            <input type="text" class="form-control" id="id_last_name" name="last_name" required>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="id_username">Username</label>
                            <input type="text" class="form-control" id="id_username" name="username" required>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="id_password">Password</label>
                            <input type="password" class="form-control" id="id_password" name="password" required>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="id_emp_id">Employee ID</label>
                            <input type="text" class="form-control" id="id_emp_id" name="emp_id" required>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="id_email">Email Address</label>
                            <input type="email" class="form-control" id="id_email" name="email" required>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="id_profile_image">Profile Image</label>
                            <input type="file" class="form-control-file" id="id_profile_image" name="profile_image">
                        </div>
                        <div class="form-group col-md-6">
                            <label for="id_name">Full Name</label>
                            <input type="text" class="form-control" id="id_name" name="name" required>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-custom btn-block">Add HR</button>
                </form>
            </div>
        </div>
    </div>
</body>

{% endblock %}

templates/hr/hr_dashboard.html
{% extends 'hr/hrbase.html' %} 
{% load widget_tweaks %} 
{% block content %}
<style>
    .bg-c-blue {
        background: #104f66;
      }
  
      .bg-c-green {
        background: #4c51bf;
      }
  
      .bg-c-yellow {
        background: #53616e;
      }
  
      .bg-c-pink {
        background: #3186ca;
      }
      @media only screen and (max-width: 600px) {
        .container{
            display:grid !important;
        }
      }
</style>
<div class="container">
    <h1>DASHBOARD</h1>
    <div class="row">
        <div class="col-md-4 mb-4">
            <a href="/admin-dashboard/employee-list/" class="text-white text-decoration-none">
                <div class="card bg-c-blue text-white h-100">
                    <div class="card-body">
                        <h6 class="mb-4">Total Employee</h6>
                        <h2 class="d-flex justify-content-between">
                            <i class="fas fa-user-graduate"></i><span>{{total_employee}}</span>
                        </h2>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-md-4 mb-4">
            <a href="hr-list/" class="text-white text-decoration-none">
                <div class="card bg-c-green text-white h-100">
                    <div class="card-body">
                        <h6 class="mb-4">Total Hr</h6>
                        <h2 class="d-flex justify-content-between">
                            <i class="fas fa-chalkboard-teacher"></i><span>{{total_hr}}</span>
                        </h2>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-md-4 mb-4">
            <a href="admin-view-Pending" class="text-white text-decoration-none">
                <div class="card bg-c-pink text-white h-100">
                    <div class="card-body">
                        <h6 class="mb-4">Pending Request</h6>
                        <h2 class="d-flex justify-content-between">
                            <i class="fas fa-book"></i><span>{{12}}</span>
                        </h2>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>
<br><br>
<div class="container">
  <h1>Recent Request</h1>
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Date</th>
            <th scope="col">Phone</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          {% for val in employee %}
          <tr>
            <td>{{val.firstname}}</td>
            <td>{{val.email}}</td>
            <td>{{val.phone}}</td>
            <td>Approved</td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
</div>

<script src="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
{% endblock %}

templates/hr/hr_list.html
{% extends 'newApp/adminbase.html' %}

{% block content %}
<h2>HR List</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Employee ID</th>
            <th>Username</th>
            <th>Name</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        {% for hr in hrs %}
        <tr>
            <td>{{ hr.emp_id }}</td>
            <td>{{ hr.user.username }}</td>
            <td>{{ hr.name }}</td>
            <td>{{ hr.user.email }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/hr/hr_login.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <script src="https://kit.fontawesome.com/64d58efce2.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/login_signup.css' %}" />
    <title>Sign in Form</title>
  </head>
  <body>

    <div class="container">
      <div class="forms-container">
        <div class="signin-signup">
          <!-- For Login  -->
          <form class="sign-in-form" method="post" action="{% url 'login_user' %}">
            {% csrf_token %}
            <h2 class="title">Hr Sign in</h2>
            <!-- Display error/success messages -->
            {% if messages %}
            <div class="alert alert-primary" role="alert">
                {% for message in messages %}
                {{ message }}
                {% endfor %}
            </div>
            {% endif %}

            <div class="input-field">
              <i class="fas fa-user"></i>
              <input type="text" placeholder="Username" name="username" required/>
            </div>
            <div class="input-field">
              <i class="fas fa-lock"></i>
              <input type="password" placeholder="Password" name="password" required/>
            </div>
            <input type="submit" value="Login" class="btn solid" />
            <p class="social-text">Or Sign in with social platforms</p>
            <div class="social-media">
              <a href="#" class="social-icon">
                <i class="fab fa-facebook-f"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-twitter"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-google"></i>
              </a>
              <a href="#" class="social-icon">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </div>
          </form>
          <!-- End Login  -->
        </div>
      </div>

      <div class="panels-container">
        <div class="panel left-panel">
          <div class="content">
            <h3>WFH here</h3>
            <p>
              One of the secret benefits of using remote workers is that the work itself becomes the yardstick to judge someone’s performance.
            </p>
          </div>
          <img src="{% static 'img/log.svg' %}" class="image" alt="" />
        </div>
      </div>
    </div>
  </body>
</html>

templates/hr/hrbase.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>WFH</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
  <script src="https://kit.fontawesome.com/41bcea2ae3.js" crossorigin="anonymous"></script>
  <style>
    @import url("https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800&display=swap");

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      text-decoration: none;
      font-family: "Open Sans", sans-serif;
    }

    body {
      margin-left: 80px;
      margin-top: 80px;
      transition: margin-left 300ms cubic-bezier(0.785, 0.135, 0.15, 0.86);
    }

    section {
      padding: 20px;
    }

    header {
      width: 100%;
      height: 80px;
      background: #f5f5f5;
      display: flex;
      align-items: center;
      position: fixed;
      top: 0;
      z-index: 200;
    }

    .icon__menu {
      width: 50px;
      height: 100%;
      display: flex;
      justify-content: center;
      align-items: center;
      cursor: pointer;
    }

    .icon__menu i {
      font-size: 20px;
      color: #333;
    }

    .menu__side {
      width: 80px;
      height: 100%;
      background: #1783db;
      position: fixed;
      top: 0;
      left: 0;
      color: white;
      font-size: 20px;
      z-index: 300;
      overflow: hidden;
      overflow-y: auto;
      transition: all 300ms cubic-bezier(0.785, 0.135, 0.15, 0.86);
    }

    .menu__side::-webkit-scrollbar {
      display: none;
    }

    .menu__side {
      -ms-overflow-style: none;
      scrollbar-width: none;
    }

    .name__page {
      padding: 20px 30px;
      display: flex;
      align-items: center;
      margin-top: 10px;
    }

    .name__page img {
      width: 30px;
      height: 30px;
      margin-right: 10px;
    }

    .options__menu {
      padding: 20px 40px;
      position: absolute;
      top: 80px;
    }

    .options__menu a {
      color: #ffffffb2;
      display: block;
      transition: color 300ms;
    }

    .options__menu a:hover {
      color: white;
      text-decoration: none;
    }

    .options__menu .option {
      padding: 20px 0px;
      display: flex;
      align-items: center;
      cursor: pointer;
    }

    .options__menu .option i {
      width: 20px;
      margin-right: 20px;
    }

    .options__menu .option h4 {
      font-weight: 300;
    }

    a.selected {
      color: #fff;
    }

    .selected:before {
      content: "";
      width: 3px;
      height: 80%;
      background: white;
      position: absolute;
      top: 10%;
      left: -30px;
    }

    .body_move {
      margin-left: 250px;
    }

    .menu__side_move {
      width: 250px;
    }

    @media screen and (max-width: 760px) {
      .body_move {
        margin-left: 0px;
      }

      .menu__side_move {
        width: 80px;
        left: -80px;
      }
    }

    .submenu {
      display: none;
      padding-left: 20px;
    }

    .submenu a {
      padding: 10px 0;
      display: flex;
      align-items: center;
      color: #ffffffb2;
    }

    .submenu a:hover {
      color: white;
    }

    .submenu a i {
      width: 20px;
      margin-right: 10px;
    }

    .submenu a h4 {
      font-weight: 300;
    }
  </style>
</head>
<body id="body">
  <header>
    <div class="icon__menu">
      <i class="fas fa-bars" id="btn_open"></i>
    </div>
  </header>

  <div class="menu__side" id="menu_side">
    <div class="name__page">
      <img src="#" alt="" />
      <h4></h4>
    </div>

    <div class="options__menu">
      <a href="/admin-dashboard/" class="selected">
        <div class="option">
          <i class="fas fa-home" title="Home"></i>
          <h4>Home</h4>
        </div>
      </a>

      <div class="option" id="employee_menu">
        <i class="fas fa-user" title="Employee"></i>
        <h4>Employee</h4>
      </div>
      <div class="submenu" id="employee_submenu">
        <a href="/employees/add/">
          <i class="fas fa-user-plus"></i>
          <h4>Add Employee</h4>
        </a>
        <a href="/employees/">
          <i class="fas fa-list"></i>
          <h4>See Employee</h4>
        </a>
      </div>

      <a href="#">
        <div class="option">
          <i class="fas fa-user" title="Hrs"></i>
          <h4>Hrs</h4>
        </div>
      </a>

      <a href="#">
        <div class="option">
          <i class="fas fa-circle-notch" title="Request"></i>
          <h4>Request</h4>
        </div>
      </a>

      <a href="#">
        <div class="option">
          <i class="far fa-question-circle" title="FAQs"></i>
          <h4>FAQs</h4>
        </div>
      </a>

      <a href="#">
        <div class="option">
          <i class="far fa-envelope" title="Contact"></i>
          <h4>Contact</h4>
        </div>
      </a>

      <a href="/">
        <div class="option">
          <i class="fas fa-sign-in-alt"></i>
          <h4>Logout</h4>
        </div>
      </a>
    </div>
  </div>

  <section>  
    {% block content %}{% endblock %}
  </section>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <script>
    // Execute function on click event
    document.getElementById("btn_open").addEventListener("click", open_close_menu);
    document.getElementById("employee_menu").addEventListener("click", toggle_employee_submenu);

    // Declare variables
    var side_menu = document.getElementById("menu_side");
    var body = document.getElementById("body");
    var employee_submenu = document.getElementById("employee_submenu");

    // Event to show and hide menu
    function open_close_menu() {
      body.classList.toggle("body_move");
      side_menu.classList.toggle("menu__side_move");
    }

    // Event to toggle employee submenu
    function toggle_employee_submenu() {
      employee_submenu.classList.toggle("submenu");
      employee_submenu.style.display = employee_submenu.style.display === "none" ? "block" : "none";
    }

    // If the page width is less than 760px, hide the menu when the page is reloaded
    if (window.innerWidth < 760) {
      body.classList.add("body_move");
      side_menu.classList.add("menu__side_move");
    }

    // Making the menu responsive
    window.addEventListener("resize", function () {
      if (window.innerWidth > 760) {
        body.classList.remove("body_move");
        side_menu.classList.remove("menu__side_move");
      }

      if (window.innerWidth < 760) {
        body.classList.add("body_move");
        side_menu.classList.add("menu__side_move");
      }
    });
  </script>
</body>
</html>